.Dd 2001-12-09
.Dt TROPHY 6
.Os "Debian GNU/Linux"
.\" Manual page created by Guus Sliepen <guus@sliepen.warande.net>
.Sh NAME
.Nm trophy
.Nd A 2D car racing action game.
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
.Nm
is a single-player racing game for Linux. Even though the goal is
basically to finish the laps as the first,
.Nm
is an action game which
offers much more than just a race. Lots of extras enable "unusual" features
for races such as shooting, putting mines and many others.
.Sh CONTROLS
.Bl -tag -width indent
.It Arrow Up
Accelerate.
.It Arrow Down
Decelerate. Don't use.
.It Arrow Left
Steer to the left.
.It Arrow Right
Steer to the right.
.It A
Turbo. Boosts speed while pressed (as long as there still is turbo fuel left).
Use it to overtake other cars or catch up if you've fallen behind.
.It C
Drop bomb. Bombs will explode after a second. Use it to damage other cars.
.It X
Shoot. Fires your machinegun straight ahead. Make sure you are pointed towards another car.
.It Space
Horn. Useless but fun anyway.
.It Escape
Stop race, go back to previous menu or quit game.
.El
.Sh FILES
.Bl -tag -width indent
.It Pa ~/trophy/
Contains the game saves
.El
.Sh AUTHOR
.Nm
has been written by
.An Andrew Mustun, 
.An Matthieu Lecesne and
.An Colin Pitrat
.Pp
This manual page was written by
.An Guus Sliepen <guus@sliepen.warande.net> and
.An Matthieu Lecesne
